### ISSUE TITLE
Downloading files

### ISSUE THREAD

**Issue by ghost** [ingolemo/drider#3]
Im having a hard time understanding the install instructions for what i need to do with 3dstool and all the others

**Comment by ingolemo** [comment]
If you just want to install drider then you don't need to build it yourself; you can download it from the [releases](https://github.com/ingolemo/drider/releases) page.

If you do want to build your own version then you need to install those tools and run `make`. By "install" I mean that you need to put the executables [somewhere](https://en.wikipedia.org/wiki/PATH_(variable)) that `make` can find them.
